using System;

namespace ConsoleApp.Problems
{
    // Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    // 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    // By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

    public class Problem2
    {
        private int _previousTerm;
        private int _currentTerm;
        private int _result;

        public Problem2()
        {
            _previousTerm = 1;
            _currentTerm = 2;
            _result = _currentTerm;
        }

        public void Solve()
        {
            while (_currentTerm < 4000000)
            {
                int nextTerm = GetNextTerm();
                UpdateTerms(nextTerm);
                AddToResultIfTermIsEven();
            }

            Console.WriteLine(_result);
        }

        private void AddToResultIfTermIsEven()
        {
            if (IsEven(_currentTerm))
                _result += _currentTerm;
        }

        private void UpdateTerms(int nextTerm)
        {
            _previousTerm = _currentTerm;
            _currentTerm = nextTerm;
        }


        private int GetNextTerm()
        {
            return _previousTerm + _currentTerm;
        }

        private bool IsEven(int second)
        {
            return second % 2 == 0;
        }
    }
}
